
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: [username]
    password: [password]
    url: jdbc:mysql://[ip]/store?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    mode: HTML5
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.store.system.mapper: debug